config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'photos#index'
  resources :photos do
    resources :comments, only: [:create, :destroy]
    resources :favarites, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :photo
  belongs_to :user

  validates :text, presence: true
end

app/models/favarite.rb
class Favarite < ApplicationRecord
  belongs_to :user
  belongs_to :photo
  validates_uniqueness_of :photo_id, scope: :user_id
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favarites, dependent: :destroy
  has_many :favarited_users, through: :favarites, source: :user

  has_one_attached :image

  validates :nickname, presence: true
  validates :title, presence: true
  validates :memo, presence: true
  validates :image, presence: true
  
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :photos, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favarites, dependent: :destroy
  has_many :favarited_photos, through: :favarites, source: :photo

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true

  def already_favarited?(photo)
    favarites.exists?(photo_id: photo.id)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  # def after_sign_in_path_for(_resource)
  #   pages_show_path
  # end

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end

    # def sign_in_required
    #   redirect_to new_user_session_url unless user_signed_in?
    # end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # before_action :set_comment, only: [:destroy]

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to photo_path(@comment.photo)
    else
      @photo = @comment.photo
      @comments = @photo.comments.includes(:user)
      render template: 'photos/show'
    end
  end

  def destroy
    @comment = current_user.comments.find_by(id: params[:id])
    @comments.destroy
    redirect_to photo_path(@comment.photo)
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, photo_id: params[:photo_id])
  end

  # def set_comment
  # end
end

app/controllers/favarites_controller.rb
class FavaritesController < ApplicationController

  def create
    @favarite = current_user.favarites.create(photo_id: params[:photo_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @favarite = Favarite.find_by(photo_id: params[:photo_id], user_id: current_user.id)
    @favarite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:edit, :show, :destroy, :update]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @photos = Photo.includes(:user).order(created_at: :desc)
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user = current_user
    if @photo.save
      redirect_to root_path, notice: '投稿が完了しました。'
    else
      render :new
    end
  end

  def update
    if @photo.update(photo_params)
      redirect_to root_path, notice: '投稿の更新が完了しました。'
    else
      render :edit
    end
  end

  def show
    @comment = Comment.new
    @comments = @photo.comments.includes(:user)
    @favarite = Favarite.new
  end

  def edit
  end

  def destroy
    @photo.destroy
    redirect_to root_path, notice: '投稿の削除が完了しました。'
  end

  private

  def photo_params
    params.require(:photo).permit(:nickname, :title, :image, :memo).merge(user_id: current_user.id)
  end

  def set_photo
    @photo = Photo.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @photos = @user.photos.includes(:user).order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favarites_helper.rb
module FavaritesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SATB</title>
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "devise/shared/header", resource: resource %>
    <%= yield %>
    <%= render "devise/shared/footer", resource: resource %>
  </body>
</html>

app/views/photos/_favarites.html.erb
 <% if current_user.already_favarited?(@photo) %>
  <%= link_to photo_favarite_path(@photo), method: :delete do %>
    <span style="color:red;">いいね❤︎</span>
  <% end %>
  <%= @photo.favarites.count %>
<% else %>
  <%= link_to photo_favarites_path(@photo), method: :post do %>
    <span>いいね❤︎</span>
  <% end %>
  <%= @photo.favarites.count %>
<% end %>

app/views/photos/_photo.html.erb
<div class="card">
  <%= link_to image_tag(@photo.image, class: :card__image ), photo_path(@photo.id),size: "280x280"%>
  <div class="card__body">
    作成者のページ
    <%= link_to @photo.title, photo_path(@photo.id), method: :get, class: :card__title%>
    <p class="card__summary">
      <%= @photo.memo %>
    </p>
    <%= link_to @photo.user.name, user_path(@photo.user_id), class: :card__user %>
  </div>
</div>

app/views/photos/_postin.html.erb
<%= link_to(new_photo_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>投稿する</span>
  <%= image_tag('10.png' , size: '65x50' ,class: "purchase-btn-icon") %>
<% end %>

app/views/photos/edit.html.erb
<div class="postin">
  <div class="page-top">
    <%= form_with model: @photo, local: true do |f| %>
      <div class="postin-form-left">
        <%= render "devise/shared/error_messages", resource: resource %>
        <div class="field">
          <%= f.label :Nickname, "ニックネーム" %><br />
          <%= f.text_field :nickname %>
        </div>
        <div class="field">
          <%= f.label :Title, "タイトル" %><br />
          <%= f.text_field :title %>
        </div>
        <div class="field">
          <%= f.label :Image, "画像" %><br />
          <%= f.file_field :image %>
        </div>
        <div class="field">
          <%= f.label :Memo, "メモ"%><br />
          <%= f.text_area :memo, rows: "3" %>
        </div>
        <div class="actions">
          <%= f.submit "SEND", class: :form__btn%>
        </div>
      <% end %>
    </div>
  </div>
  <div class="page-top">
    <div class="postin-form">
    </div>
  </div>
</div>
</div>

app/views/photos/index.html.erb
<div class="main">
  <div id="home" class="big-bg">
    <div class="home-content wrapper">
      <h2 class="page-title">shogun-authorized<br>
        trading book
        <p>そうだ 御朱印集めに行こう</p>
      </h2>
    </div>
  </div>
  <!-- /#home -->
  <div id="room" class="post">
    <div class="room-content wrapper">
      <div class="post-gest">
        <%= image_tag('一覧.png', class: "post-image") %>
      </div>
    </div>
  </div>
  <div class='wrapper grid'>
    <% @photos.each do |photo| %>
      <%= link_to photo_path(photo.id), method: :get do %>
        <div class='items'>
          <%= image_tag photo.image, class: "item-img" %><br>
          <div class="item-main">
            <%= photo.title %><br>
            by  <%= photo.nickname %>さん<br>
          <div class="item-count">
            いいねカウント<%= photo.favarites.count %> 
        </div>
        </div>
     <% end %>
    </div>
   <% end %>
  </div>
</div>
<%= render partial: "postin"%>

app/views/photos/new.html.erb
<div class="postin">
  <div class="page-top">
    <%= form_with model: @photo, local: true do |f| %>
      <div class="postin-form-left">
        <%= render "devise/shared/error_messages", resource: resource %>
        <div class="field">
          <%= f.label :Nickname, "ニックネーム" %><br />
          <%= f.text_field :nickname %>
        </div>
        <div class="field">
          <%= f.label :Title, "タイトル" %><br />
          <%= f.text_field :title %>
        </div>
        <div class="field">
          <%= f.label :Image, "画像" %><br />
          <%= f.file_field :image %>
        </div>
        <div class="field">
          <%= f.label :Memo, "メモ"%><br />
          <%= f.text_area :memo, rows: "3" %>
        </div>
        <div class="actions">
          <%= f.submit "SEND", class: :form__btn%>
        </div>
      <% end %>
    </div>
  </div>
  <div class="page-top">
    <div class="postin-form">
    </div>
  </div>
</div>
</div>

app/views/photos/show.html.erb
<div class="container wrapper">
  <div class="container-main">
    <%= image_tag @photo.image, class: "item-img" %><br>
    <%= @photo.title %><br>
    by  <%= @photo.nickname %>さん<br>
    <% if user_signed_in? && current_user.id == @photo.user_id %>
      <div class="photo__manage">
        <%= link_to "編集する", edit_photo_path(@photo.id), class: :photo__btn %>/
        <%= link_to "削除する", photo_path(@photo.id),  method: :delete, class: :photo__btn %>
      </div>
    <% end %>
    <% if user_signed_in? %>
      <%= form_with(model: [@photo, @comment], local: true) do |f| %>
        <%= render partial: "favarites" %>
        <div class="field">
          <%= f.label :comment, "コメント投稿" %><br />
          <%= f.text_area :text,rows: "2" %><br>
        </div>
        <div class="actions-comment">
          <%= f.submit "SEND", class: :form__btn_comment %>
        </div>
      <% end %>
    <% else %>
      <strong>
        <p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p>
      </strong>
    <% end %>
  </div>
  <div class="comments-main">
    <div class="comments">
      <%= image_tag('コメント一覧.png', class: "post-image") %>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.name, "/users/#{comment.user_id}" %>：</strong>
          <%= comment.text %>
        </p>
      <% end %>
    </div>
  </div>
<h2>いいねしたユーザー</h2>
<% @photo.favarited_users.each do |user| %>
  <li><%= user.name %></li>
<% end %>
</div>

app/views/users/show.html.erb
<div class="show wrapper">
  <div class="show-page">
    <div class="table">
      <%= "#{@user.name}" %>さんの投稿一覧
    </div>
  </div>
  <div class='grid'>
    <% @photos.each do |photo|  %>
      <div class='items'>
        <%= link_to photo_path(photo.id), method: :get do %>
          <%= image_tag photo.image, class: "item-img" %><br>
          <div class="item-main">
            タイトル:  <%= photo.title %><br>
            メモ:  <%= photo.memo %><br>
            作成日:  <%= l photo.created_at, format: :short %></td>
        </div>
        <% if current_user.already_favarited?(photo) %>
          <%= link_to photo_favarite_path(photo), method: :delete do %>
            <i class="fas fa-heart"></i>
            <span style="color:red;">❤︎</span>
          <% end %>
          <%= photo.favarites.count %>
        <% else %>
          <%= link_to photo_favarites_path(photo), method: :post do %>
            <i class="far fa-heart"></i>
            <span>❤︎</span>
          <% end %>
          <%= photo.favarites.count %>
        <% end %>
      <% end %>
    </div>
  <% end %>
  </div>

  <h3>いいねしている投稿</h3>
  <div class="grid">
    <% @user.favarited_photos.each do |photo| %>
      <%= link_to photo_path(photo.id), method: :get do %>
        <div class="like">
          <%= image_tag photo.image, class: "item-img-show" %><br>
          ユーザー名：<%= photo.user.name %>さん<br>
          タイトル：<%= photo.title%><br>
        </div>
      <% end %>
    <% end %>
  </div>
<% if @photos[0] == nil %>
  <div class='list'>
    <%= link_to(new_photo_path) do %>
      <div class='item-info'>
        <%= image_tag('画像投稿.png', class: "post-image-mypage") %>
      </div>
    </div>
  <% end %>
</div>
<% end %>
</div>
<%= render partial: "photos/postin"%>